// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {Roboto} from 'next/font/google'
import { Work_Sans } from "next/font/google";

const roboto = Roboto({
  subsets:["latin"],
  variable: "--font--roboto",
})

const workSans = Work_Sans({subsets: ['latin'], variable: '--font-work-sans',})


export default function RootLayout({children}){
    return ( <html lang="en">
      <body className={`${roboto.variable} ${workSans.variable}`}>
        {/* <h1>Hello Layout</h1> */}
        {children}
      </body> 
    </html>
    ) 
}

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {


//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }





